/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GameMode = IDL.Variant({
  'freeKick' : IDL.Null,
  'penalty' : IDL.Null,
  'kickoff' : IDL.Null,
});
export const HighScoreEntry = IDL.Record({
  'player' : IDL.Principal,
  'mode' : GameMode,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayerBestScore' : IDL.Func(
      [IDL.Principal, GameMode],
      [IDL.Opt(HighScoreEntry)],
      ['query'],
    ),
  'getPlayerTopScores' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'freeKick' : IDL.Opt(HighScoreEntry),
          'penalty' : IDL.Opt(HighScoreEntry),
          'kickoff' : IDL.Opt(HighScoreEntry),
        }),
      ],
      ['query'],
    ),
  'getTopScores' : IDL.Func([GameMode], [IDL.Vec(HighScoreEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitHighScore' : IDL.Func([IDL.Nat, IDL.Int, GameMode], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GameMode = IDL.Variant({
    'freeKick' : IDL.Null,
    'penalty' : IDL.Null,
    'kickoff' : IDL.Null,
  });
  const HighScoreEntry = IDL.Record({
    'player' : IDL.Principal,
    'mode' : GameMode,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayerBestScore' : IDL.Func(
        [IDL.Principal, GameMode],
        [IDL.Opt(HighScoreEntry)],
        ['query'],
      ),
    'getPlayerTopScores' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'freeKick' : IDL.Opt(HighScoreEntry),
            'penalty' : IDL.Opt(HighScoreEntry),
            'kickoff' : IDL.Opt(HighScoreEntry),
          }),
        ],
        ['query'],
      ),
    'getTopScores' : IDL.Func([GameMode], [IDL.Vec(HighScoreEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitHighScore' : IDL.Func([IDL.Nat, IDL.Int, GameMode], [], []),
  });
};

export const init = ({ IDL }) => { return []; };