/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameMode = { 'freeKick' : null } |
  { 'penalty' : null } |
  { 'kickoff' : null };
export interface HighScoreEntry {
  'player' : Principal,
  'mode' : GameMode,
  'score' : bigint,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayerBestScore' : ActorMethod<
    [Principal, GameMode],
    [] | [HighScoreEntry]
  >,
  'getPlayerTopScores' : ActorMethod<
    [Principal],
    {
      'freeKick' : [] | [HighScoreEntry],
      'penalty' : [] | [HighScoreEntry],
      'kickoff' : [] | [HighScoreEntry],
    }
  >,
  'getTopScores' : ActorMethod<[GameMode], Array<HighScoreEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitHighScore' : ActorMethod<[bigint, bigint, GameMode], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];